services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - ${WSRS_DATABASE_PORT:-5432}:5432
    environment:
      POSTGRES_USER: ${WSRS_DATABASE_USER}
      POSTGRES_PASSWORD: ${WSRS_DATABASE_PASSWORD}
      POSTGRES_DB: ${WSRS_DATABASE_NAME}
    volumes:
      - postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - 8070:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@encoders.com.br
      PGADMIN_DEFAULT_PASSWORD: 4Dm1n+Pws
    volumes:
      - pgadmin:/var/lib/pgadmin

volumes:
  postgres:
    driver: local
  pgadmin:
    driver: local